#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libo
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments $*

unset COMP_FLAGS LINK_FLAGS

# make (non-shared by default) object
wmake $targetType

#------------------------------------------------------------------------------
